### ISSUE TITLE
Version 1.0 Roadmap

### ISSUE THREAD

**Issue by be5invis** [be5invis/Iosevka#5]
- [x] **Cover basic Greek glyphs.** -- done in 0.0.5
- [x] **Cover Cyrillic glyphs used for Russian.** -- done in 0.0.6
- [x] **Cover all letters in WGL4.**
- [x] **Complete WGL4.**
- [x] **Powerline glyphs.** -- done in 0.0.7
- [ ] **Interface for third-party glyphs.**
- [ ] **Support ligation.** I mean, `sub f i' by i.ligation`. It is better than `sub f i by f_i`.

**Comment by be5invis** [comment]
r0.1.0 Checkpoint: 5 of 7 are completed.
