### ISSUE TITLE
Asymmetric 8, like Fira Code or FF Meta

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#867]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

Shown below are closeups of Iosevka's standard 8 and Fira Code's asymmetric 8, and I've drawn lines between the holes to point it out. In one hand it a sort of &aleph;-like shape at the cross-section. From another perspective, it looks like an `s` but with the terminals curving inward and meeting one another.

Most _serif_ fonts (even Times New Roman) do have these styles as standard, and thus adapted in **humanist** sans-serif fonts such as Fira Code and FF Meta makes it unique and at the same time beautiful to see.

<img alt="8" src="https://user-images.githubusercontent.com/16898444/106410886-dceb5800-647e-11eb-9c40-e0b8c94fb3a4.png">

**Comment by be5invis** [comment]
This shape is very hard to construct. Put in backlog.

**Comment by be5invis** [comment]
> and thus adapted in humanist sans-serif fonts

Iosevka is **not** Humanist styled. It is closer to Neo-Grotesque.

**Comment by NoxUltima** [comment]
Oh. Oops.
